version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: utec_postgres
    environment:
      POSTGRES_DB: utec
      POSTGRES_USER: utecsuruser
      POSTGRES_PASSWORD: utecsurpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U utecsuruser -d utec"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: utec_pdi_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/utec
      - SPRING_DATASOURCE_USERNAME=utecsuruser
      - SPRING_DATASOURCE_PASSWORD=utecsurpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SERVER_PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - spring_net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  spring_net:
